version: "3.3"
services:
  consul:
    depends_on:
    - gentry
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: >
        {
          "bind_addr": "eth0",
          "client_addr": "0.0.0.0",
          "enable_script_checks": true,
          "service": {
            "checks": [
              {
                "interval": "10s",
                "tcp": "localhost:8080"
              }
            ],
            "name": "web",
            "port": 8080
          },
          "ui": true,
          "watches": [
            {
              "handler": "/go/gentry",
              "type": "checks"
            }
          ]
        }
    image: consul
    ports:
    - 8500:8500
    volumes:
    - shared:/go
  gentry:
    build: .
    command: go build -v
    volumes:
    - shared:/go/bin
volumes:
  shared:
